### ISSUE TITLE
Readme.Rmd missing in master branch

### ISSUE THREAD

**Issue by jhoeffler** [subugoe/hoad#200]

**Comment by maxheld83** [comment]
Thanks for reporting this!

In the current design, there *is* no `README.Rmd`, but only a `README.md`.
Previously (I think?) there was a `README.Rmd` which was then `rmarkdown::render()`ed to `README.md`.

This is sometimes used when the `README.md` absolutely *has* to show things that were programmatically generated.
WIth a proper documentation site now powered by [{pkgdown}](http://pkgdown.r-lib.org) and up at http://subugoe.github.io/hoad/ this is no longer necessary.

The `README.md` now includes only very brief static information about the project.

`README.Rmd`s rendered through to `README.md` also have the disadvantage that they require you to `git commit` programmatically created, and therefore derivative files.
As much as absolutely possible, this should be avoided, because it makes the `git diff`s hard to read and leads to general confusion and is very, very error prone.

(The one exception to this rule is currently everything in `man/`, which *is* programmatically created from {roxygen} comments, and therefore derivative, but must remain in the git source because it will otherwise break `remotes::install_github()` and friends, which is a community standard).

So I'm closing this because `README.Rmd` isn't actually missing 🙂.
